name: Create and Publish Packages

'on':
  push:

  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0

      - name: Create Packages
        run: ./build.ps1

      - name: Publish Packages
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        run: >
          dotnet nuget push **/*.nupkg
          --api-key '${{ secrets.NUGET_API_KEY }}'
          --source '${{ vars.NUGET_URL }}'
          --skip-duplicate
