name: Create and Publish Packages

on:
  push:

  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Create Packages
        run: |
          ./build.ps1

      - name: Publish Packages
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          nuget push .packages/*.nupkg
            -Source 'https://nuget.pkg.github.com/dcjulian29/index.json'
            -ApiKey ${{secrets.NUGET_API_KEY}}
            -skipDuplicate
